为2024新本科毕业论文格式提供新的模板
whutug/whu-thesis pull request #248
Opened 2024-03-25 21:28 UTC by cylqqqcyl

为2024新本科毕业论文格式提供新的模板，基于本repo进行了一些修改以符合格式，主要修改了.cls文件，希望能merge到一个新的branch（例如2024-bachelor）上

2024-03-26 00:04 UTC, xkwxdyy commented on 武汉大学本科生毕业论文（设计）参考模板（2024315）.pdf
PDF 是哪来的，有什么链接之类的支撑它的可参考性吗。作为参考的模板一定要有可靠性，否则用户“不敢用”。

2024-03-26 00:08 UTC, xkwxdyy commented
> 为2024新本科毕业论文格式提供新的模板，基于本repo进行了一些修改以符合格式，主要修改了.cls文件，希望能merge到一个新的branch（例如2024-bachelor）上

我看了你 push 的 README，你把主页的 README 改成类似于专为计算机学院更新的，大概率你参考的模板也是计算机学院提供的吧，你这里 `为2024新本科毕业论文格式提供新的模板` 就说的有问题了。因为别的学院是怎么更新的，甚至有没有更新你应该都不清楚。

2024-04-05 12:07 UTC, zhengxiongli08 commented
我是物院的，学院发布了相同的书写印刷规范和本科毕业论文模板，该模板是通用的，希望维护者能够update一下现在的模板。主要是封面页和前面几页的布局排版方便有一些变化。
[论文书写规范与参考模板-20240315.zip](https://github.com/whutug/whu-thesis/files/14884607/-20240315.zip)

2024-04-05 13:07 UTC, zhengxiongli08 commented
> > 我是物院的，学院发布了相同的书写印刷规范和本科毕业论文模板，该模板是通用的，希望维护者能够update一下现在的模板。主要是封面页和前面几页的布局排版方便有一些变化。 [论文书写规范与参考模板-20240315.zip](https://github.com/whutug/whu-thesis/files/14884607/-20240315.zip)
> 
> 可以看一下这个repo的和物院的模版有无相似可借鉴之处
> 
> https://github.com/cylqqqcyl/whu-thesis-2024/tree/main

是一样的，我看了你之前提交的[文件](https://github.com/cylqqqcyl/whu-thesis-2024/blob/c0e7efcf1691ab0a9cf95fa9627dfe677dd25afc/%E6%AD%A6%E6%B1%89%E5%A4%A7%E5%AD%A6%E6%9C%AC%E7%A7%91%E7%94%9F%E6%AF%95%E4%B8%9A%E8%AE%BA%E6%96%87%EF%BC%88%E8%AE%BE%E8%AE%A1%EF%BC%89%E5%8F%82%E8%80%83%E6%A8%A1%E6%9D%BF%EF%BC%882024315%EF%BC%89.pdf)，完全一致。

2024-04-06 04:35 UTC, SwitWu requested changes

2024-04-06 04:35 UTC, SwitWu commented on whu-thesis.cls
> -    tocdepth       = 2,  % 目录层级数
`tocdepth` 的对应关系：

+ 0: chapter
+ 1: section
+ 2: subsection

论文要求最多展示三级标题，因此设置 `tocdepth = 2` 才是正确的

2024-04-06 04:35 UTC, SwitWu commented on whu-thesis.cls
> +    advisor-name   .tl_gset:N    = \g__whu_info_advisor_name,
命名需要符合 LaTeX3 规范，将 `g__whu_info_advisor_name` 改为 `g__whu_info_advisor_name_tl`

2024-04-06 04:35 UTC, SwitWu commented on .github/ISSUE_TEMPLATE/question.md
此文件需要恢复

2024-04-06 04:37 UTC, SwitWu commented
@cylqqqcyl 你先把上述几处修改一下

2024-04-06 04:54 UTC, SwitWu approved these changes

2024-04-06 04:54 UTC, merged

2024-04-06 04:56 UTC, xkwxdyy commented
> @cylqqqcyl 你先把上述几处修改一下

不需要，你 merge 之后自己改掉，然后在 commit 就行。

2024-04-06 05:00 UTC, SwitWu commented
我才发现我可以直接操作他 folk 过去的仓库